version: "3.8"

services:
  service_rabbitmq:
    image: rabbitmq:3.10-management
    container_name: container_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
