[tool.poetry]
name = "tests_rabbitmq"
version = "0.1.0"
description = ""
authors = ["Jorge Vasconcelos "]

[tool.poetry.dependencies]
python = "^3.9"
pika = "^1.3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
